definitions:
  entity.Location:
    properties:
      latitude:
        type: string
      longitude:
        type: string
      user:
        type: string
    required:
    - latitude
    - longitude
    type: object
  error.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  error.HTTPError200:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: Item created successfully
        type: string
    type: object
  error.HTTPError404:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: Not Found
        type: string
    type: object
  error.HTTPError500:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Server Error
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a mini store application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/locations/:
    get:
      consumes:
      - application/json
      description: get all location by json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.HTTPError200'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.HTTPError404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.HTTPError500'
      security:
      - ApiKeyAuth: []
      summary: get all locations
      tags:
      - Locations
    post:
      consumes:
      - application/json
      description: add by json location
      parameters:
      - description: Location Data
        in: body
        name: location
        required: true
        schema:
          $ref: '#/definitions/entity.Location'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.HTTPError200'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.HTTPError404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.HTTPError500'
      security:
      - ApiKeyAuth: []
      summary: Add a location
      tags:
      - Locations
  /api/v1/locations/{id}:
    get:
      consumes:
      - application/json
      description: get location by ID
      parameters:
      - description: Location ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.HTTPError200'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.HTTPError404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.HTTPError500'
      security:
      - ApiKeyAuth: []
      summary: Show a location
      tags:
      - Locations
  /api/v1/locations/{id}/user:
    get:
      consumes:
      - application/json
      description: get location by User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/error.HTTPError200'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.HTTPError404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.HTTPError500'
      security:
      - ApiKeyAuth: []
      summary: Show locations by a user
      tags:
      - Locations
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
