// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clock/clock.proto

package clock

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClockinRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockinRequest) Reset()         { *m = ClockinRequest{} }
func (m *ClockinRequest) String() string { return proto.CompactTextString(m) }
func (*ClockinRequest) ProtoMessage()    {}
func (*ClockinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a46ae1a40e92652, []int{0}
}

func (m *ClockinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockinRequest.Unmarshal(m, b)
}
func (m *ClockinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockinRequest.Marshal(b, m, deterministic)
}
func (m *ClockinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockinRequest.Merge(m, src)
}
func (m *ClockinRequest) XXX_Size() int {
	return xxx_messageInfo_ClockinRequest.Size(m)
}
func (m *ClockinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClockinRequest proto.InternalMessageInfo

func (m *ClockinRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClockinRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ClockinResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Timein               string   `protobuf:"bytes,4,opt,name=timein,proto3" json:"timein,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockinResponse) Reset()         { *m = ClockinResponse{} }
func (m *ClockinResponse) String() string { return proto.CompactTextString(m) }
func (*ClockinResponse) ProtoMessage()    {}
func (*ClockinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a46ae1a40e92652, []int{1}
}

func (m *ClockinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockinResponse.Unmarshal(m, b)
}
func (m *ClockinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockinResponse.Marshal(b, m, deterministic)
}
func (m *ClockinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockinResponse.Merge(m, src)
}
func (m *ClockinResponse) XXX_Size() int {
	return xxx_messageInfo_ClockinResponse.Size(m)
}
func (m *ClockinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClockinResponse proto.InternalMessageInfo

func (m *ClockinResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClockinResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClockinResponse) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ClockinResponse) GetTimein() string {
	if m != nil {
		return m.Timein
	}
	return ""
}

type ClockoutRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Break                string   `protobuf:"bytes,3,opt,name=break,proto3" json:"break,omitempty"`
	Errande              string   `protobuf:"bytes,4,opt,name=errande,proto3" json:"errande,omitempty"`
	Reason               string   `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockoutRequest) Reset()         { *m = ClockoutRequest{} }
func (m *ClockoutRequest) String() string { return proto.CompactTextString(m) }
func (*ClockoutRequest) ProtoMessage()    {}
func (*ClockoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a46ae1a40e92652, []int{2}
}

func (m *ClockoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockoutRequest.Unmarshal(m, b)
}
func (m *ClockoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockoutRequest.Marshal(b, m, deterministic)
}
func (m *ClockoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockoutRequest.Merge(m, src)
}
func (m *ClockoutRequest) XXX_Size() int {
	return xxx_messageInfo_ClockoutRequest.Size(m)
}
func (m *ClockoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClockoutRequest proto.InternalMessageInfo

func (m *ClockoutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClockoutRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClockoutRequest) GetBreak() string {
	if m != nil {
		return m.Break
	}
	return ""
}

func (m *ClockoutRequest) GetErrande() string {
	if m != nil {
		return m.Errande
	}
	return ""
}

func (m *ClockoutRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ClockoutResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Timeout              string   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockoutResponse) Reset()         { *m = ClockoutResponse{} }
func (m *ClockoutResponse) String() string { return proto.CompactTextString(m) }
func (*ClockoutResponse) ProtoMessage()    {}
func (*ClockoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a46ae1a40e92652, []int{3}
}

func (m *ClockoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockoutResponse.Unmarshal(m, b)
}
func (m *ClockoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockoutResponse.Marshal(b, m, deterministic)
}
func (m *ClockoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockoutResponse.Merge(m, src)
}
func (m *ClockoutResponse) XXX_Size() int {
	return xxx_messageInfo_ClockoutResponse.Size(m)
}
func (m *ClockoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClockoutResponse proto.InternalMessageInfo

func (m *ClockoutResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClockoutResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClockoutResponse) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ClockoutResponse) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type ClockDetails struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Timein               string   `protobuf:"bytes,4,opt,name=timein,proto3" json:"timein,omitempty"`
	Timeout              string   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockDetails) Reset()         { *m = ClockDetails{} }
func (m *ClockDetails) String() string { return proto.CompactTextString(m) }
func (*ClockDetails) ProtoMessage()    {}
func (*ClockDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a46ae1a40e92652, []int{4}
}

func (m *ClockDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockDetails.Unmarshal(m, b)
}
func (m *ClockDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockDetails.Marshal(b, m, deterministic)
}
func (m *ClockDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockDetails.Merge(m, src)
}
func (m *ClockDetails) XXX_Size() int {
	return xxx_messageInfo_ClockDetails.Size(m)
}
func (m *ClockDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ClockDetails proto.InternalMessageInfo

func (m *ClockDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClockDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClockDetails) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ClockDetails) GetTimein() string {
	if m != nil {
		return m.Timein
	}
	return ""
}

func (m *ClockDetails) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func init() {
	proto.RegisterType((*ClockinRequest)(nil), "clock.ClockinRequest")
	proto.RegisterType((*ClockinResponse)(nil), "clock.ClockinResponse")
	proto.RegisterType((*ClockoutRequest)(nil), "clock.ClockoutRequest")
	proto.RegisterType((*ClockoutResponse)(nil), "clock.ClockoutResponse")
	proto.RegisterType((*ClockDetails)(nil), "clock.ClockDetails")
}

func init() { proto.RegisterFile("clock/clock.proto", fileDescriptor_7a46ae1a40e92652) }

var fileDescriptor_7a46ae1a40e92652 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x31, 0x4f, 0x03, 0x31,
	0x0c, 0x85, 0xe9, 0xd1, 0xeb, 0x09, 0x0b, 0x15, 0xb0, 0xa0, 0x8a, 0x98, 0x50, 0x26, 0xa6, 0x22,
	0x81, 0xc4, 0xc0, 0x0a, 0x13, 0x63, 0xf9, 0x05, 0xe9, 0x9d, 0x91, 0xac, 0x5e, 0x93, 0x92, 0xe4,
	0x18, 0x58, 0xf8, 0xeb, 0xe8, 0x9c, 0x14, 0x38, 0x26, 0x10, 0x5d, 0x22, 0xbf, 0x27, 0x59, 0xdf,
	0xb3, 0x63, 0x38, 0xa9, 0x5b, 0x57, 0xaf, 0xae, 0xe4, 0x9d, 0x6f, 0xbc, 0x8b, 0x0e, 0x4b, 0x11,
	0xfa, 0x16, 0xa6, 0xf7, 0x7d, 0xc1, 0x76, 0x41, 0x2f, 0x1d, 0x85, 0x88, 0x53, 0x28, 0xb8, 0x51,
	0xa3, 0x8b, 0xd1, 0xe5, 0xc1, 0xa2, 0xe0, 0x06, 0x4f, 0xa1, 0xa4, 0xb5, 0xe1, 0x56, 0x15, 0x62,
	0x25, 0xa1, 0x6b, 0x38, 0xfa, 0xec, 0x0b, 0x1b, 0x67, 0x03, 0xfd, 0xae, 0x11, 0x11, 0xc6, 0x8d,
	0x89, 0xa4, 0xf6, 0xc5, 0x94, 0x1a, 0x67, 0x30, 0x89, 0xbc, 0x26, 0xb6, 0x6a, 0x2c, 0x6e, 0x56,
	0xfa, 0x3d, 0x43, 0x5c, 0x17, 0xff, 0x94, 0xae, 0x77, 0x97, 0x9e, 0xcc, 0x2a, 0x53, 0x92, 0x40,
	0x05, 0x15, 0x79, 0x6f, 0x6c, 0x43, 0x99, 0xb3, 0x95, 0x7d, 0x00, 0x4f, 0x26, 0x38, 0xab, 0xca,
	0x14, 0x20, 0x29, 0xfd, 0x0c, 0xc7, 0x5f, 0x01, 0xfe, 0x3d, 0xa6, 0x82, 0xaa, 0x1f, 0xcc, 0x75,
	0x71, 0xcb, 0xcf, 0x52, 0xbf, 0xc1, 0xa1, 0x70, 0x1e, 0x28, 0x1a, 0x6e, 0xc3, 0xee, 0x57, 0xf9,
	0x9d, 0x5d, 0x0e, 0xd8, 0xd7, 0x8f, 0x99, 0xfd, 0x44, 0xfe, 0x95, 0x6b, 0xc2, 0x3b, 0xa8, 0xf2,
	0xcf, 0xe2, 0xd9, 0x3c, 0x5d, 0xcc, 0xf0, 0x42, 0xce, 0x67, 0x3f, 0xed, 0xb4, 0x19, 0xbd, 0xb7,
	0x9c, 0xc8, 0x6d, 0xdd, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0x96, 0x86, 0x44, 0x33, 0x70, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClockServiceClient is the client API for ClockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClockServiceClient interface {
	Clockin(ctx context.Context, in *ClockinRequest, opts ...grpc.CallOption) (*ClockinResponse, error)
}

type clockServiceClient struct {
	cc *grpc.ClientConn
}

func NewClockServiceClient(cc *grpc.ClientConn) ClockServiceClient {
	return &clockServiceClient{cc}
}

func (c *clockServiceClient) Clockin(ctx context.Context, in *ClockinRequest, opts ...grpc.CallOption) (*ClockinResponse, error) {
	out := new(ClockinResponse)
	err := c.cc.Invoke(ctx, "/clock.ClockService/Clockin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClockServiceServer is the server API for ClockService service.
type ClockServiceServer interface {
	Clockin(context.Context, *ClockinRequest) (*ClockinResponse, error)
}

// UnimplementedClockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClockServiceServer struct {
}

func (*UnimplementedClockServiceServer) Clockin(ctx context.Context, req *ClockinRequest) (*ClockinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clockin not implemented")
}

func RegisterClockServiceServer(s *grpc.Server, srv ClockServiceServer) {
	s.RegisterService(&_ClockService_serviceDesc, srv)
}

func _ClockService_Clockin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClockinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClockServiceServer).Clockin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clock.ClockService/Clockin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClockServiceServer).Clockin(ctx, req.(*ClockinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clock.ClockService",
	HandlerType: (*ClockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Clockin",
			Handler:    _ClockService_Clockin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clock/clock.proto",
}
